name: Metrics
on:
  schedule: [{cron: "0 16 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: Vyodour
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Makassar
          config_display: large
          config_padding: 0, 8%
          
          config_order: introduction, base, skyline, languages, isocalendar, topics, habits, activity, followup, notable, gists, repositories, stars, traffic, reactions, people, support, stargazers, achievements, music

          plugin_introduction: yes
          plugin_introduction_title: yes 

          plugin_skyline: yes
          plugin_skyline_year: 2024
          plugin_skyline_frames: 60
          plugin_skyline_quality: 0.5

          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, vue, jupyter notebook
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_details: lines, percentage
          plugin_languages_indepth: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_limit: 0
          plugin_topics_sort: random 

          plugin_habits: yes
          plugin_habits_from: 500
          plugin_habits_days: 180
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          plugin_habits_languages_limit: 8
          
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_visibility: all

          plugin_followup: yes
          plugin_followup_sections: repositories, user
          
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit, pull_request, review
          
          plugin_gists: yes
          
          plugin_repositories: yes
          plugin_repositories_featured: Vyodour
          plugin_repositories_pinned: 2
          
          plugin_stars: yes
          plugin_stars_limit: 4
          
          plugin_traffic: yes
          
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: count, percentage

          plugin_people: yes
          plugin_people_types: followers, following
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_shuffle: yes

          plugin_support: yes

          plugin_lines: yes
          
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
          plugin_music_limit: 4
          plugin_music_mode: recent
          plugin_music_played_at: yes
